### ISSUE TITLE
More information about the project

### ISSUE THREAD

**Issue by pratikbhd** [andyvandy/972project#1]
Hey guys @andyvandy @JoshSV,

I couldn't find a better way to contact you. I'm working on a similar project, implementing the ONS algorithm on a Deep RL architecture. 
I was going through this project and wanted to know how the code in the `code` directory is related to the Jupyter scripts in the `scripts` directory?

**Comment by andyvandy** [comment]
Hey sorry for the massive delay @pratikbhd - I realize that this reply is in all likelihood too late. The goal of the `code `folders was to ultimately run these strategies live with a small amount of crypto. This code was written some time ago but  what happened was that we scaled back our ambitions and ultimately submitted what was added to the `scripts `folder.  

I've emailed you the final pdf writeup that I believe we submitted which should provide hopefully provide context. 

I've added my email to my github account as well so that I should be easier to reach in the future. :)

**Comment by pratikbhd** [comment]
Hey! No worries about the delay. I ended up doing the same thing by scaling down the project proposal to a simpler model which ended up being similar to what you guys did in the `scripts` folder.

Thank you for sending me the pdf writeup! This was a project on a class of my final semester and I've already graduated now but I do intend to get back to this project to hopefully improve it. Your writeup will definitely come in handy then.

I'll reach out to you if I need some clarification or help about your writeup or code later on. 
Thanks!
